version: '3.9'
services:
  web:
    container_name: demo-01-node
    restart: always
    build: .
    ports:
      - "5001:3000"
    links:
      - mongo
    volumes:
      - .:/usr/src/app
  mongo:
    container_name: demo-01-db
    image: mongo
    ports:
      - "5002:27017"
    logging:
      driver: none